apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: github-actions-runner-role
  namespace: runner
  labels:
    app: github-runners
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec", "pods/log", "services", "endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
