name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    runs-on: runner-set
    
    steps:
     - name: Checkout code
       uses: actions/checkout@v3

     - name: create a file
       run: echo "Hello World" > hi.txt

     - name: Show file
       run: cat hi.txt

     - name: Where
       run: ls -lart 
