name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    runs-on: runner-set
    
    steps:
     - name: Checkout code
       uses: actions/checkout@v3

     - name: Create a file in a persistent directory
       run: echo "Hello World" > /home/ubuntu/hi.txt
